#Makefile: Arianna Vacca

#Target
default: all
#Compile .c to .o
all:
	gcc -Wall -o awget awget.c
	gcc -Wall -o ss ss.c
#Compile ss
ss:
	gcc -Wall -o ss ss.c
#Compile awget
awget:
	gcc -Wall -o awget awget.c
#Clean
clean:
	rm -f awget.o ss.o
	rm -f awget ss